apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: techtalksweb
  namespace: AzureBootCamp2018
  labels:
    run: webfront

spec:
  replicas: 1
  selector:
    matchLabels:
      run: webfront
  
  template:
    metadata:
      labels:
        run: webfront
    spec:
      containers:
      - name: techtalksweb
        image: nileshgule/techtalksweb
        ports:
        - containerPort: 80
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst