FROM microsoft/aspnetcore-build AS build-env

WORKDIR /app

COPY TechTalksProcessor /TechTalksProcessor/
COPY TechTalksModel /TechTalksModel/

# COPY NuGet.config ./

WORKDIR /TechTalksProcessor
RUN dotnet restore

#COPY . ./

RUN dotnet publish --configuration Release --output releaseOutput --no-restore

#build runtime image
FROM microsoft/aspnetcore

WORKDIR /TechTalksProcessor

COPY --from=build-env /TechTalksProcessor/releaseOutput ./

ENTRYPOINT ["dotnet", "TechTalksProcessor.dll"]
