kind: Service
apiVersion: v1
metadata:
  namespace: abc2018sg
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer  
    # type: NodePort      
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
  selector:
    app: rabbitmq