version: '3'

services:
  sql.data:
    image: nileshgule/sqlclient
    build:
      context: ../TechTalksDB
      dockerfile: Dockerfile
    
  webmvc:
    image: nileshgule/techtalksweb
    build:
      context: ../TechTalksWeb
      dockerfile: Dockerfile
    depends_on: 
      - techtalks.api
    ports:
      - "80:80"
      
  techtalks.api:
    image: nileshgule/techtalksapi
    build:
      context: ../TechTalksAPI
      dockerfile: Dockerfile
    depends_on:
      - sql.data
    ports:
      - "8080:8080"

  techtalks.processor:
    image: nileshgule/techtalksprocessor
    build:
      context: ../TechTalksProcessor
      dockerfile: Dockerfile

  
