version: '3'

services:
  sql.data:
    image: nileshgule/sqlclient
    # hostname: 'sql2017'
    # container_name: sql2017
    build:
      context: ../TechTalksDB
      dockerfile: Dockerfile
    
  webmvc:
    image: nileshgule/techtalksweb
    # container_name: techtalksweb
    build:
      context: ../TechTalksWeb
      dockerfile: Dockerfile
    depends_on: 
      - techtalks.api
    ports:
      - "80:80"
      
  techtalks.api:
    image: nileshgule/techtalksapi
    # container_name: TechTalksAPI
    build:
      context: ../TechTalksAPI
      dockerfile: Dockerfile
    depends_on:
      - sql.data
    ports:
      - "8080:8080"

  
