version: '3'

services:
  sql.data:
    image: nileshgule/sqlclient
    build:
      context: ../TechTalksDB
      dockerfile: Dockerfile
    
  webmvc:
    image: nileshgule/techtalksweb
    build:
      context: ../TechTalksWeb
      dockerfile: Dockerfile
    depends_on: 
      - techtalks.api
    ports:
      - "80:80"
      
  techtalks.api:
    image: nileshgule/techtalksapi
    build:
      context: ..
      dockerfile: Dockerfile-TechTalksAPI
    depends_on:
      - sql.data
    ports:
      - "8080:8080"

  techtalks.processor:
    image: nileshgule/techtalksprocessor
    build:
      context: ..
      dockerfile: Dockerfile-TechTalksProcessor

  techtalks.elkprocessor:
    image: nileshgule/techtalkselkprocessor
    build:
      context: ..
      dockerfile: Dockerfile-TechTalksELKProcessor

  
