apiVersion: apps/v1beta1
kind: Deployment

metadata:
  name: techtalksapi
  namespace: AzureBootCamp2018
  labels:
    run: techtalksapi

spec:
  replicas: 1
  selector:
    matchLabels:
      run: techtalksapi
  
  template:
    metadata:
      labels:
        run: techtalksapi
    spec:
      initContainers:
        - name: init-myservice
          image: nileshgule/sqlclient
          command:
            - "sh"
            - "-c"
            - "/opt/mssql-tools/bin/sqlcmd -S mssql-deployment -U sa -P January2018 -d master -i initialize-database.sql"
      containers:
      - name: techtalksapi
        image: nileshgule/techtalksapi
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst