---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db-deployment
  namespace: abc2018sg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sql2017
        image: microsoft/mssql-server-linux
        ports:
        - name: dbport
          containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: January2018
        - name: MSSQL_PID
          value: Developer