---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sqlserverstatefulset
  namespace: abc2018sg
spec:
  serviceName: db-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sql2017
        image: microsoft/mssql-server-linux
        imagePullPolicy: IfNotExists
        resources:
          requests:
            memory: "2Gi"
          limits:
            memory: "3Gi"
        ports:
        - name: dbport
          containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: January2018
          # valueFrom:
          #   secretKeyRef:
          #     name: sqlsecret
          #     key: sapassword
        - name: MSSQL_PID
          value: Developer
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: techtalksdb-data