apiVersion: v1
kind: Service
metadata:
  name: db-deployment
  namespace: abc2018sg
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: LoadBalancer
  # type: NodePort